### ISSUE TITLE
(request) Add support for other OSes

### ISSUE THREAD

**Issue by lovebug0706** [werwolf2303/SpotifyXP#17]
My XP partition crapped out on me after an update, so i decided to install Arch Linux. I got JRE 20-1 from yay (command for arch user repository downloads) and I couldnt figure out for the life of me how to use snap so i couldnt install regular Spotify, so i tried this again. It gave me this error.
```
SpotifyAPI [ERROR ] error.configuration.failedcreate
SpotifyAPI [ERROR ] Failed to create SpotifyXP folder in AppData
SpotifyAPI [THROWABLE ] java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
SpotifyAPI [THROWABLE ] java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:356)
SpotifyAPI [THROWABLE ] java.base/java.io.File.createNewFile(File.java:1045)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.<init>(Config.java:33)
SpotifyAPI [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:58)
SpotifyAPI [ERROR ] Cant create configfile
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.open0(Native Method)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
SpotifyAPI [THROWABLE ] java.base/java.io.FileWriter.<init>(FileWriter.java:67)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.<init>(Config.java:41)
SpotifyAPI [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:58)
SpotifyAPI [ERROR ] Cant write to configfile
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newByteChannel(Files.java:379)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newByteChannel(Files.java:431)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newInputStream(Files.java:159)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.<init>(Config.java:48)
SpotifyAPI [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:58)
SpotifyAPI [ERROR ] Failed to load configfile
SpotifyAPI [THROWABLE ] java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
SpotifyAPI [THROWABLE ] java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:356)
SpotifyAPI [THROWABLE ] java.base/java.io.File.createNewFile(File.java:1045)
SpotifyAPI [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:142)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.open0(Native Method)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
SpotifyAPI [THROWABLE ] java.base/java.io.FileWriter.<init>(FileWriter.java:67)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.write(Config.java:57)
SpotifyAPI [THROWABLE ] com.spotifyxp.dialogs.LoginDialog$4.actionPerformed(LoginDialog.java:101)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processEvent(Component.java:6385)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.processEvent(Container.java:2266)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
SpotifyAPI [ERROR ] Cant write to configfile
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newByteChannel(Files.java:379)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newByteChannel(Files.java:431)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newInputStream(Files.java:159)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.write(Config.java:63)
SpotifyAPI [THROWABLE ] com.spotifyxp.dialogs.LoginDialog$4.actionPerformed(LoginDialog.java:101)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processEvent(Component.java:6385)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.processEvent(Container.java:2266)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
SpotifyAPI [ERROR ] Failed to load configfile
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.open0(Native Method)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
SpotifyAPI [THROWABLE ] java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
SpotifyAPI [THROWABLE ] java.base/java.io.FileWriter.<init>(FileWriter.java:67)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.write(Config.java:57)
SpotifyAPI [THROWABLE ] com.spotifyxp.dialogs.LoginDialog$4.actionPerformed(LoginDialog.java:102)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processEvent(Component.java:6385)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.processEvent(Container.java:2266)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
SpotifyAPI [ERROR ] Cant write to configfile
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
SpotifyAPI [THROWABLE ] java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newByteChannel(Files.java:379)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newByteChannel(Files.java:431)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
SpotifyAPI [THROWABLE ] java.base/java.nio.file.Files.newInputStream(Files.java:159)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.write(Config.java:63)
SpotifyAPI [THROWABLE ] com.spotifyxp.dialogs.LoginDialog$4.actionPerformed(LoginDialog.java:102)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
SpotifyAPI [THROWABLE ] java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.processEvent(Component.java:6385)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.processEvent(Container.java:2266)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
SpotifyAPI [THROWABLE ] java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
SpotifyAPI [THROWABLE ] java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
SpotifyAPI [THROWABLE ] java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
SpotifyAPI [ERROR ] Failed to load configfile
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.io.FileNotFoundException: null/SpotifyXP/credentials.json (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)
	at com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:448)
	at com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.authenticate(Session.java:342)
	at com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.access$600(Session.java:78)
	at com.spotifyxp.deps.xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1058)
	at com.spotifyxp.utils.PlayerUtils.buildPlayer(PlayerUtils.java:47)
	at com.spotifyxp.api.SpotifyAPI$Player.<init>(SpotifyAPI.java:87)
	at com.spotifyxp.Initiator.main(Initiator.java:161)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.spotifyxp.deps.xyz.gianlu.librespot.player.Player.isReady()" because "this.player" is null
	at com.spotifyxp.api.SpotifyAPI$Player.<init>(SpotifyAPI.java:99)
	at com.spotifyxp.Initiator.main(Initiator.java:161)
Exception in thread "session-packet-receiver" java.lang.NullPointerException: Cannot read field "in" because the return value of "com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.access$800(com.spotifyxp.deps.xyz.gianlu.librespot.core.Session)" is null
	at com.spotifyxp.deps.xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:1421)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Exception in thread "session-packet-receiver" java.lang.NullPointerException: Cannot read field "in" because the return value of "com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.access$800(com.spotifyxp.deps.xyz.gianlu.librespot.core.Session)" is null
	at com.spotifyxp.deps.xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:1421)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

IDK if you can fix this or not, or if you will fix it since im on a different OS, but it would help!
- MacBack
Edit: Realized its probably because of Appdata not showing up on Arch. I mean, what can you expect, its not XP.

**Comment by werwolf2303** [comment]
I have already have half implemented this. It will be in version 1.8

**Comment by lovebug0706** [comment]
Thank you!
