### ISSUE TITLE
[ERROR] Cant get past Initializing Config

### ISSUE THREAD

**Issue by lovebug0706** [werwolf2303/SpotifyXP#26]
Im using Mac OS X 10.10.5 Yosemite on a MacBook Pro mid 2012 with Java 8 Version 371. Heres the error, i dont know whats going on. IDK if it has to do with the appdata folder or something
```
SpotifyAPI [ERROR ] error.configuration.failedcreate
SpotifyAPI [THROWABLE ] com.spotifyxp.exception.ExceptionDialog.open(ExceptionDialog.java:14)
SpotifyAPI [THROWABLE ] com.spotifyxp.configuration.Config.<init>(Config.java:34)
SpotifyAPI [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:112)

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"
```
If you can fix this, that would be lovely because Mac OS X 10.10.5 doesnt support Spotify anymore.

EDIT: I tried Java 7 Version 80 and it gave a different error, idk if its because of the java version or not. Java 8 got the farthest, so im sticking with it. Heres the error for java 7 in case:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/spotifyxp/Initiator : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by werwolf2303** [comment]
MacOS is not supported only Linux and Windows.
